### ISSUE TITLE
training data csv file

### ISSUE THREAD

**Issue by buttercutter** [bsamseth/tictacNET#2]
May I know how should I interpret your [training data csv file](https://github.com/bsamseth/tictacNET/blob/master/tictactoe-data.csv) ?

I do not quite understand the columns naming style.

**Comment by bsamseth** [comment]
Hi!

Sure thing. Taking the first line as an example:
```csv
x1,x2,x3,x4,x5,x6,x7,x8,x9,o1,o2,o3,o4,o5,o6,o7,o8,o9,m1,m2,m3,m4,m5,m6,m7,m8,m9,turn,score
1,0,1,0,1,0,0,1,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1
```
The first nine columns (the `xn` columns) indicate whether there is an X at the n'th square or not. The next nine do the same for the O's. Togheter these 18 columns tell you what the board looks like. In this example, you get

```
X | O | X
O | X | O
O | X | 
```

The next nine columns tell you what is the best move(s). In this case the only legal move has a 1, the remaining are marked with a 0. 

Lastly you get who's turn it is (0 for X and 1 for O), and the score of the board. The score refers to what the theoretically best score the player can get with optimal play. In this case, the score is 1 because X will be able to win this position with optimal play (in this case there's only one legal move, but nonetheless). A draw is a score of 0, a forced loss is score -1. 

I hope that clears things up for you!

**Comment by buttercutter** [comment]
It seems that you have [4520 training cases](https://github.com/bsamseth/tictacNET/blob/master/tictactoe-data.csv#L4521) in the csv file.

I believe 4520 is not the fully-exhaustive training dataset ?  What about the test dataset ?

**Comment by buttercutter** [comment]
Ok, I saw you are allocating [0.2 (20 percent) of 4520 cases](https://github.com/bsamseth/tictacNET/blob/master/tictacnet.py#L27) for test purposes.

Why `input_dim` [only includes](https://github.com/bsamseth/tictacNET/blob/master/tictacnet.py#L32) `X` ?  What about `moves` ?

**Comment by bsamseth** [comment]
The moves are the output, they don't belong in the inputs. If you did, the model would quickly realize that it should ignore everything else and just output the moves, because you are giving it the "answer" as part of the input. Try it and see what happens! :)

**Comment by buttercutter** [comment]
ok, [inputs](https://github.com/bsamseth/tictacNET/blob/master/tictacnet.py#L19-L20) are board features plus turn , [output](https://github.com/bsamseth/tictacNET/blob/master/tictacnet.py#L22-L23) is preferred next move.

What about `score` ?

**Comment by buttercutter** [comment]
I suppose a good NN combines both `policy` (preferred next move) and `value` (good score) ?

By the way, is this how you [generate the csv training dataset](https://github.com/bsamseth/tictacNET/blob/master/tictactoe.py#L148-L159) ?

I do not quite understand what [functionality](https://github.com/bsamseth/tictacNET/blob/master/tictactoe.py#L136-L143) does `def bitboard_to_list(board)` actually perform ?
